name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ gmanand1999 }}
        password: ${{ Giri@9047 }}

    - name: Build the Docker image
      run: docker build -t your-dockerhub-username/your-image-name:latest .

    - name: Push the Docker image
      run: docker push your-dockerhub-username/your-image-name:latest
